### ISSUE TITLE
No gerbers

### ISSUE THREAD

**Issue by leaderit** [pmandes/atari-130xe-replica#1]
No additional files, just a picture and BOM

**Comment by pmandesubs** [comment]
All files will be made available (KiCad project: schematic, PCB layout, and production gerbers) as soon as the prototype is launched and the correctness of all elements has been verified.

**Comment by pmandes** [comment]
All files will be made available (KiCad project: schematic, PCB layout, and production gerbers) as soon as the prototype is launched and the correctness of all elements has been verified.
